title: saor docs
description: Documentation for saor operating system, a Cosmos-based operating system made in C#.
theme: just-the-docs

url: https://g1o.tech

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
